### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by arcondello** [ValeryTyumen/planar_ising#1]
I was wondering if it would be possible to add a license? Some of my colleagues and I are potentially interested in using your library. Thanks!

**Comment by ValeryTyumen** [comment]
Sure - https://github.com/ValeryTyumen/planar_ising/commit/5a1803487e1dd59c5d5e790cc949b7234bf52ac8. Please let me know if you have any questions. Also this is an ongoing project (a newer preprint can be found in https://arxiv.org/abs/1906.06431), so we are ready for discussion and collaboration. Thanks!

**Comment by arcondello** [comment]
Thank you!
